In [1]:
pip install numpy

# CREATING 1D,2D AND 3D ARRAYS


In [2]:
import numpy as np

In [3]:
arr1d = np.array([1,2,3,4,5])

In [4]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [5]:
print(arr1d)

[1 2 3 4 5]


In [6]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


# Creating Arrays with Default values

In [9]:
zeros = np.zeros((3,3)) # 3x3 matrix filled with zeros.
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones = np.ones((2,2)) # 2x2 matrix filled with ones.
print(ones)

[[1. 1.]
 [1. 1.]]


In [11]:
identity = np.eye(3)  # 3x3 identity matrix
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
random_arr = np.random.rand(3,3) # 3x3 matrix with random variables
print(random_arr)

[[0.48903658 0.21836569 0.9033117 ]
 [0.29544123 0.43687631 0.52002831]
 [0.2967223  0.39183706 0.65255148]]


# Creating a Range of Values

In [13]:
arr_range = np.arange(1,10,2)
print(arr_range)

[1 3 5 7 9]


In [14]:
arr_linspace = np.linspace(0,10,5) # The last value denotes the no. of samples
print(arr_linspace)

[ 0.   2.5  5.   7.5 10. ]


# Array Properties

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(arr.shape)

(2, 3)


In [18]:
print(arr.size)

6


In [19]:
print(arr.dtype)

int32


In [21]:
print(arr.ndim)

2


# Reshaping and Flattening Arrays

In [22]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
print(arr.shape)

(2, 3)


In [25]:
reshaped = arr.reshape(3,2) # change shape

In [26]:
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
flattened = arr.flatten() # convert to 1D array

In [28]:
print(flattened)

[1 2 3 4 5 6]


# Indexing and Slicing

In [29]:
arr = np.array([10,20,30,40,50])

In [30]:
print(arr[1])

20


In [31]:
print(arr[-1])

50


In [32]:
print(arr[1:4])

[20 30 40]


In [33]:
print(arr[:3])

[10 20 30]


In [34]:
print(arr[::-1])

[50 40 30 20 10]


# For Multi-Dimensional Arrays

In [36]:
arr2d = np.array([[10,20,30],[40,50,60]])
arr2d


array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
print(arr2d[1,2])

60


In [39]:
print(arr2d[:,1])

[20 50]


In [40]:
print(arr2d[0,:])

[10 20 30]
