In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

# array operations

In [4]:
arr= np.array([1,2,3,4,5])
print(arr**2)

[ 1  4  9 16 25]


#Elementwise operations

In [5]:
arr1=np.array([1,2,3])
arr2= np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


#AGGERATION

In [7]:
arr=np.array([[1,2,3],[4,5,6]])#2x2 matrix
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))
print(np.sum(arr,axis=0))# sum of columns
print(np.sum(arr,axis=1))#sum of rows

45
5.0
9
2.581988897471611
6.666666666666667
[12 15 18]
[ 6 15 24]


In [9]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])# 3x3 matrix
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))
print(np.sum(arr,axis=0))# sum of columns
print(np.sum(arr,axis=1))#sum of rows

45


# BROADCASTING (Numpy allows operations on arrays of different shapes)

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
vector=np.array([1,2,3])
print(arr)
print(vector)

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [15]:
print(arr+vector)

[[2 4 6]
 [5 7 9]]


# STACKING AND SPLITTING ARRAYS 

In [17]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])


array([1, 2, 3])

In [19]:
stacked=np.vstack((arr1,arr2))#vertical stacking
print(stacked)


[[1 2 3]
 [4 5 6]]


In [22]:
hstacked=np.hstack((arr1,arr2))#horizontal stacking
print(hstacked)

[1 2 3 4 5 6]


In [20]:
stacked.shape

(2, 3)

# BOOLEAN MASKING AND FILTERING

In [23]:
arr= np.array([1,2,3,4,5,6])
mask= arr >3 # mask is an array containing bool values.

In [24]:
print(arr[mask])

[4 5 6]


In [25]:
print(arr[arr%2 == 0])

[2 4 6]


# list cannot be used to mask in numpy
#l=[1,2,3,4]
#mask>3
#print(l[mask])

# SAVING AND LOADING ARRAYS

In [31]:
np.save('array.npy',arr) # save to file

In [32]:
loaded_arr = np.load('array.npy') # load from file
print(loaded_arr)

[1 2 3 4 5 6]


In [33]:
# To save/load as text files

np.savetxt('array.txt',arr,delimiter=",")

In [34]:
loaded_arr = np.loadtxt('array.txt',delimiter = ',')
print(loaded_arr)

[1. 2. 3. 4. 5. 6.]


#WORKING WITH RANDOM NUMBERS

In [35]:
print(np.random.rand(3,3))

[[0.83818435 0.61278976 0.62235731]
 [0.38147863 0.99461864 0.43871975]
 [0.57541158 0.01885656 0.17721892]]


In [37]:
print(np.random.randint(1,10,(3,3)))

[[5 4 8]
 [6 9 9]
 [5 3 8]]


In [38]:
print(np.random.normal(0,1,(2,2)))

[[-0.60895216  0.08830737]
 [-0.49897258  0.64945951]]
